### ISSUE TITLE
Some methods are missing from the pip package

### ISSUE THREAD

**Issue by PavelBastov** [MelchiSalins/pyindependentreserve#7]
Hello there,

thank you for maintaining this API! I'm playing around with it and I noticed that a couple of methods are missing from the pip package:

## Public API
`get_valid_order_types()`

## Private API
`get_brokerage_fees()`

Could you please update the package?

Thank you.

**Comment by PeerLabs** [comment]
Hi, 

I have noticed the same specifically differences with get_transactions() in the Private API

Thanks

**Comment by MelchiSalins** [comment]
Yeah, I'll cut a new release in a bit.

**Comment by MelchiSalins** [comment]
Version 0.2.0 is out with the new methods in it.
