### ISSUE TITLE
NameError: name 'PrivateMethods' is not defined

### ISSUE THREAD

**Issue by songproducer** [MelchiSalins/pyindependentreserve#8]
> api = PrivateMethods("api_key", "api_secret")

produces this error:
>NameError: name 'PrivateMethods' is not defined

**Comment by MelchiSalins** [comment]
have you imported the package as 

`import * from independentreserve ` ?

**Comment by ricnus** [comment]
Hello,

I am having this same issue.

Edit:  I have found that it should be 
`api = ir.PrivateMethods("api_key", "api_secret")`
The ir. was missing

**Comment by songproducer** [comment]
Thanks @ricnus that worked!
